import './globals.css'
import { Montserrat } from 'next/font/google'

const montserrat = Montserrat({ weight: '400', subsets: ['latin'] })

export const metadata = {
  title: 'Course Management System',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  )
}
